name: Build and Push Docker Image

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub (use GitHub Secrets for credentials)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t twila/project_a_server:${{ github.sha }} .

      # Tag the image as latest
      - name: Tag Docker Image as Latest
        run: docker tag twila/project_a_server:${{ github.sha }} twila/project_a_server:latest

      # Push both tags
      - name: Push Docker Image with Commit SHA
        run: docker push twila/project_a_server:${{ github.sha }}

      - name: Push Latest Docker Image
        run: docker push twila/project_a_server:latest
